apiVersion: 1

datasources:
  - name: AI-Quant Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      maxOpenConns: 4
      maxIdleConns: 1
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    editable: false
    isDefault: true
